import = [
  "/home/suraj/.nvm/versions/node/v20.15.1/lib/node_modules/alacritty-themes/themes/Tokyonight_Night.toml",
]

[font]
size = 9

[font.normal]
family = "JetBrains Mono"
style = "Italic"

[window]
opacity = 0.90
padding.x = 10
padding.y = 10
